# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6680464d0042845e762612b29eb4cb0b1296826a2af7e058fa94e0dfe3cca4ac02df7f2241fc2c6241dee92a58c497f8b4dbe4067febe5adc033ad8619af41f7

test:
  secret_key_base: 502d3736a2835e509f48a177fad8ed71ef306bbc7d4f54e3b886e0dbe2e79e83d220e00d428889d20c4e8424be4a05a8e02a465e87cd8a05c347475cb7adc799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
